[2023-10-11T01:56:31.606+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gx.gx_validate_pg manual__2023-10-11T01:56:26.677529+00:00 [queued]>
[2023-10-11T01:56:31.610+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gx.gx_validate_pg manual__2023-10-11T01:56:26.677529+00:00 [queued]>
[2023-10-11T01:56:31.610+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-11T01:56:31.616+0000] {taskinstance.py:1380} INFO - Executing <Task(GreatExpectationsOperator): gx_validate_pg> on 2023-10-11 01:56:26.677529+00:00
[2023-10-11T01:56:31.625+0000] {standard_task_runner.py:57} INFO - Started process 235 to run task
[2023-10-11T01:56:31.627+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gx', 'gx_validate_pg', 'manual__2023-10-11T01:56:26.677529+00:00', '--job-id', '1396', '--raw', '--subdir', 'DAGS_FOLDER/gx.py', '--cfg-path', '/tmp/tmp9r12x1yr']
[2023-10-11T01:56:31.627+0000] {standard_task_runner.py:85} INFO - Job 1396: Subtask gx_validate_pg
[2023-10-11T01:56:31.651+0000] {task_command.py:415} INFO - Running <TaskInstance: gx.gx_validate_pg manual__2023-10-11T01:56:26.677529+00:00 [running]> on host c658243ed4ce
[2023-10-11T01:56:31.693+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gx' AIRFLOW_CTX_TASK_ID='gx_validate_pg' AIRFLOW_CTX_EXECUTION_DATE='2023-10-11T01:56:26.677529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-11T01:56:26.677529+00:00'
[2023-10-11T01:56:31.693+0000] {great_expectations.py:570} INFO - Running validation with Great Expectations...
[2023-10-11T01:56:31.693+0000] {great_expectations.py:572} INFO - Instantiating Data Context...
[2023-10-11T01:56:31.697+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-10-11T01:56:31.718+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/base_data_context.py:158: DeprecationWarning: DataContext and BaseDataContext are deprecated as of v0.17.10 and will be removed in v0.20. Please use gx.get_context instead.
  warnings.warn(

[2023-10-11T01:56:31.732+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/serializable_data_context.py:226: UserWarning: Warning. An existing `great_expectations.yml` was found here: /opt/***/include/gx.
    - No action was taken.
  warnings.warn(message)

[2023-10-11T01:56:31.732+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/serializable_data_context.py:236: UserWarning: Warning. An existing `config_variables.yml` was found here: /opt/***/include/gx/uncommitted.
    - No action was taken.
  warnings.warn(message)

[2023-10-11T01:56:31.736+0000] {file_data_context.py:224} INFO - FileDataContext loading fluent config
[2023-10-11T01:56:31.737+0000] {config.py:185} INFO - Loading 'datasources' ->
[]
[2023-10-11T01:56:31.777+0000] {great_expectations.py:585} INFO - Creating Checkpoint...
[2023-10-11T01:56:31.779+0000] {great_expectations.py:604} INFO - Running Checkpoint...
[2023-10-11T01:56:31.793+0000] {validator.py:1496} INFO - 	1 expectation(s) included in expectation_suite.
[2023-10-11T01:56:31.798+0000] {logging_mixin.py:151} WARNING - Calculating Metrics:   0%|          | 0/2 [00:00<?, ?it/s]
[2023-10-11T01:56:31.798+0000] {logging_mixin.py:151} WARNING - Calculating Metrics:   0%|          | 0/2 [00:00<?, ?it/s]
[2023-10-11T01:56:31.798+0000] {logging_mixin.py:151} WARNING - Calculating Metrics:  50%|#####     | 1/2 [00:00<00:00, 2855.21it/s]
[2023-10-11T01:56:31.799+0000] {logging_mixin.py:151} WARNING - Calculating Metrics:  50%|#####     | 1/2 [00:00<00:00, 1452.32it/s]
[2023-10-11T01:56:31.800+0000] {logging_mixin.py:151} WARNING - Calculating Metrics: 100%|##########| 2/2 [00:00<00:00, 910.42it/s] 
[2023-10-11T01:56:31.800+0000] {logging_mixin.py:151} WARNING - Calculating Metrics: 100%|##########| 2/2 [00:00<00:00, 827.44it/s]
[2023-10-11T01:56:31.800+0000] {logging_mixin.py:151} WARNING - Calculating Metrics: 100%|##########| 2/2 [00:00<00:00, 783.54it/s]
[2023-10-11T01:56:31.801+0000] {logging_mixin.py:151} WARNING - Calculating Metrics: 100%|##########| 2/2 [00:00<00:00, 743.08it/s]
[2023-10-11T01:56:32.012+0000] {great_expectations.py:618} INFO - GE Checkpoint Run Result:
{
  "run_id": {
    "run_name": "gx_validate_pg_2023-10-11::01:56:31",
    "run_time": "2023-10-11T01:56:31.781281+00:00"
  },
  "run_results": {
    "ValidationResultIdentifier::strawberry_suite/gx_validate_pg_2023-10-11::01:56:31/20231011T015631.781281Z/0d80ad7e0671deaa07380041882558f5": {
      "validation_result": {
        "success": false,
        "results": [
          {
            "success": false,
            "expectation_config": {
              "expectation_type": "expect_table_row_count_to_be_between",
              "kwargs": {
                "min_value": 2,
                "max_value": 3,
                "batch_id": "0d80ad7e0671deaa07380041882558f5"
              },
              "meta": {},
              "expectation_context": {
                "description": null
              }
            },
            "result": {
              "observed_value": 5
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          }
        ],
        "evaluation_parameters": {},
        "statistics": {
          "evaluated_expectations": 1,
          "successful_expectations": 0,
          "unsuccessful_expectations": 1,
          "success_percent": 0.0
        },
        "meta": {
          "great_expectations_version": "0.17.21",
          "expectation_suite_name": "strawberry_suite",
          "run_id": {
            "run_name": "gx_validate_pg_2023-10-11::01:56:31",
            "run_time": "2023-10-11T01:56:31.781281+00:00"
          },
          "batch_spec": {
            "data_asset_name": "strawberries",
            "table_name": "strawberries",
            "batch_identifiers": [
              "airflow_run_id"
            ],
            "module_name": "great_expectations.datasource.data_connector.asset",
            "class_name": "Asset",
            "schema_name": "public",
            "sorters": {},
            "type": null
          },
          "batch_markers": {
            "ge_load_time": "20231011T015631.784069Z"
          },
          "active_batch_definition": {
            "datasource_name": "postgres_default_configured_sql_datasource",
            "data_connector_name": "default_configured_asset_sql_data_connector",
            "data_asset_name": "strawberries",
            "batch_identifiers": {}
          },
          "validation_time": "20231011T015631.793615Z",
          "checkpoint_name": "strawberries.strawberry_suite.chk",
          "validation_id": null,
          "checkpoint_id": null
        }
      },
      "actions_results": {
        "store_validation_result": {
          "class": "StoreValidationResultAction"
        },
        "store_evaluation_params": {
          "class": "StoreEvaluationParametersAction"
        },
        "update_data_docs": {
          "local_site": "file:///opt/airflow/include/great_expectations/uncommitted/data_docs/local_site/validations/strawberry_suite/gx_validate_pg_2023-10-11%3A%3A01%3A56%3A31/20231011T015631.781281Z/0d80ad7e0671deaa07380041882558f5.html",
          "class": "UpdateDataDocsAction"
        }
      }
    }
  },
  "checkpoint_config": {
    "action_list": [
      {
        "name": "store_validation_result",
        "action": {
          "class_name": "StoreValidationResultAction"
        }
      },
      {
        "name": "store_evaluation_params",
        "action": {
          "class_name": "StoreEvaluationParametersAction"
        }
      },
      {
        "name": "update_data_docs",
        "action": {
          "class_name": "UpdateDataDocsAction",
          "site_names": []
        }
      }
    ],
    "default_validation_id": null,
    "site_names": null,
    "profilers": [],
    "slack_webhook": null,
    "evaluation_parameters": {},
    "name": "strawberries.strawberry_suite.chk",
    "config_version": 1.0,
    "runtime_configuration": {},
    "ge_cloud_id": null,
    "expectation_suite_ge_cloud_id": null,
    "notify_on": null,
    "validations": [],
    "template_name": null,
    "batch_request": {},
    "notify_with": null,
    "module_name": "great_expectations.checkpoint",
    "class_name": "Checkpoint",
    "run_name_template": "gx_validate_pg_2023-10-11::01:56:31",
    "expectation_suite_name": "strawberry_suite"
  },
  "success": false
}
[2023-10-11T01:56:32.019+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 619, in execute
    self.handle_result(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 659, in handle_result
    raise AirflowException("Validation with Great Expectations failed.\n" f"Results\n {result_list}")
airflow.exceptions.AirflowException: Validation with Great Expectations failed.
Results
 {'statistics': {'evaluated_expectations': 1, 'successful_expectations': 0, 'unsuccessful_expectations': 1, 'success_percent': 0.0}, 'expectation_suite_name': 'strawberry_suite', 'batch_definition': {'datasource_name': 'postgres_default_configured_sql_datasource', 'data_connector_name': 'default_configured_asset_sql_data_connector', 'data_asset_name': 'strawberries', 'batch_identifiers': {}}}
[2023-10-11T01:56:32.021+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gx, task_id=gx_validate_pg, execution_date=20231011T015626, start_date=20231011T015631, end_date=20231011T015632
[2023-10-11T01:56:32.027+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1396 for task gx_validate_pg (Validation with Great Expectations failed.
Results
 {'statistics': {'evaluated_expectations': 1, 'successful_expectations': 0, 'unsuccessful_expectations': 1, 'success_percent': 0.0}, 'expectation_suite_name': 'strawberry_suite', 'batch_definition': {'datasource_name': 'postgres_default_configured_sql_datasource', 'data_connector_name': 'default_configured_asset_sql_data_connector', 'data_asset_name': 'strawberries', 'batch_identifiers': {}}}; 235)
[2023-10-11T01:56:32.079+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-11T01:56:32.092+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
